services:
  arithmetic-app:
    build: .
    container_name: arithmetic-app-container
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://arithmetic-app-db:5432/db_arithmetic
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - arithmetic-network
    depends_on:
      - arithmetic-db

  arithmetic-db:
    image: postgres:17
    container_name: arithmetic-app-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_arithmetic
    networks:
      - arithmetic-network
    restart: always

networks:
  arithmetic-network: